import { Navigation, Footer } from "./Components";
import { Providers } from "./store/providers";
import ReactTostify from "./shared/react-tostify";
import "./globals.css";
import "swiper/css/bundle";

export const metadata = {
  title: "Euphoria - E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <ReactTostify />
          <Navigation />
          <div className="min-h-screen">{children}</div>
          <div className="rouned mt-16 bg-slate-900">
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
